#!/bin/bash
# **************************************************************************** #
# This file is part of cmdutils: https://github.com/fdch/cmdutils
# Copyright (C) 2022 Fede Camara Halac
# **************************************************************************** #

# Daemon to check if there is an internet connection

while true
do
    echo checking internet...
    if ! ping www.google.com -c 1 >/dev/null 2>&1
    then
        echo Not connected, trying again...
        sleep 1
    else
        echo You are online.
        break
    fi
done
