#!/bin/bash
# **************************************************************************** #
# This file is part of cmdutils: https://github.com/fdch/cmdutils
# Copyright (C) 2022 Fede Camara Halac
# **************************************************************************** #

# Daemon to check if JACK has been started

while true
do
    if $(jack_lsp >/dev/null 2>&1)
    then
        jack_lsp
        break
    else
        echo "Waiting for jack client..."
        sleep 1
    fi
done

