#!/bin/bash
# **************************************************************************** #
# This file is part of cmdutils: https://github.com/fdch/cmdutils
# Copyright (C) 2022 Fede Camara Halac
# **************************************************************************** #

# Searches and destroys .DS_Store files recursively (macos only)

find . -type f -name .DS_Store -exec rm -rv {} \;
