#!/bin/sh
# **************************************************************************** #
# This file is part of cmdutils: https://github.com/fdch/cmdutils
# Copyright (C) 2022 Fede Camara Halac
# **************************************************************************** #

# Compare directories

d1=$1
d2=$2

if [ ! -d $d1 ]
then
    echo "Provide a directory in argument 1"
    exit
elif [ ! -d $d2 ]
then
    echo "Provide a directory in argument 2"
    exit
else
    echo "Comparing $d1 and $d2"
fi

diff -rq $d1 $d2
