#!/bin/bash
# **************************************************************************** #
# This file is part of cmdutils: https://github.com/fdch/cmdutils
# Copyright (C) 2022 Fede Camara Halac
# **************************************************************************** #

# Daemon to check if a file has been changed

fname=$1
id=$$

echo "$id"

function get_time()
{
    t=$(ls -Tla $fname  | cut -f 12  -d ' ')
}

get_time

o=$t

while true; do
    get_time
    if [[ "$t" != "$o" ]]
    then
        echo 1
    fi
    o=$t
    sleep 0.25
done

