#!/bin/bash
# **************************************************************************** #
# This file is part of cmdutils: https://github.com/fdch/cmdutils
# Copyright (C) 2022 Fede Camara Halac
# **************************************************************************** #

# Fix macos webcam when stuck (macos only)

echo "this will revive the camera, input pass and all is well"
sudo killall VDCAssistant
